version: 1.0.0
pidfile: ./humpback-center.pid
siteapi: http://192.168.2.80:8012/api
cluster:
    opts: [
            #"location=dev",
            "cacheroot=./cache",
            "overcommit=0.08",
            "recoveryinterval=120s",
            "createretry=1",
            "migratedelay=45s"
    ]
    discovery:
        uris: zk://192.168.2.80:2181,192.168.2.81:2181,192.168.2.82:2181
        cluster: humpback/center
        heartbeat: 8s
api:
    hosts: [":8589"]
    enablecors: true
notifications:
    endpoints:
      #- name: api
      #  url: http://127.0.0.1:8009/framework/v1/mail
      #  headers:
      #      content-type: ["application/json; charset=utf-8"]
      #  sender: xxxxx.xx.x@example.com
      #  enabled: true
      #- name: smtp
      #  host: smtp.example.com
      #  port: 25
      #  user: admin
      #  password: 123456
      #  sender: xxxxx.xx.x@example.com
      #  enabled: true
logger:
    logfile: ./logs/humpback-center.log
    loglevel: debug
    logsize: 20971520
...
