version: 1.3.4
pidfile: ./humpback-center.pid
retrystartup: true
siteapi: http://192.168.2.80:8012/api
cluster:
    opts: [
            #"location=dev",
            "cacheroot=./cache",
            "overcommit=0.08",
            "recoveryinterval=120s",
            "createretry=2",
            "migratedelay=60",
            "removedelay=500s"
    ]
    discovery:
        uris: zk://192.168.2.80:2181,192.168.2.81:2181,192.168.2.82:2181
        cluster: humpback/center
        heartbeat: 8s
api:
    hosts: [":8589"]
    enablecors: true
notifications:
    endpoints:
      #- name: api
      #  url: http://192.168.139.1:8009/framework/v1/mail
      #  headers:
      #      x-cluster-notify: ["endo"]
      #      content-type: ["application/json; charset=utf-8"]
      #  sender: humpback@newegg.com
      #  enabled: true
      #- name: smtp
      #  host: smtp.example.com
      #  port: 25
      #  user: u1
      #  password: 123456
      #  sender: humpback@newegg.com
      #  enabled: true
logger:
    logfile: ./logs/humpback-center.log
    loglevel: error
    logsize: 20971520
...
